on:
  push:

jobs:
  plan-1:
    runs-on: ubuntu-latest
    outputs:
      runner-name: ${{ steps.runner.outputs.name }}
    steps:
      - name: Set runner name
        id: runner
        run: |
          echo "name=ubuntu-latest" >> $GITHUB_OUTPUT
  apply-1:
    runs-on: ubuntu-latest
    needs: plan-1
    steps:
      - name: Show plan-1 output
        run: |
          echo "Output plan-1: ${{ needs.plan-1.outputs.runner-name}}"
  plan-2:
    runs-on: ubuntu-latest
    outputs:
      runner-name: ${{ steps.runner.outputs.name }}
    steps:
      - name: Set runner name
        id: runner
        run: |
          echo "name=windows-latest" >> $GITHUB_OUTPUT
  apply-2:
    runs-on: ubuntu-latest
    needs: [plan-2, apply-1]
    if: needs.plan-2.outputs.runner-name == 'blah-latest'
    steps:
      - name: Show plan-2 output
        run: |
          echo "Output plan-2: ${{ needs.plan-2.outputs.runner-name}}"