name: Test actions

on:
  push:
    branches:
      - main

jobs:
  test-checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: Show pwd and list files and folders BEFORE repo checkout
        run: |
          echo "Here is the pwd:"
          pwd
          echo "Here are files and folders"
          ls -la
          ls -la ../
          ls -la ../../
          docker ps -a
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Show pwd and list files and folders AFTER repo checkout
        run: |
          echo "Here is the pwd:"
          pwd
          echo "Here are files and folders"
          ls -la
      - name: Is docker installed by default
        run: docker --version
